import React, { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import Sidebar from '../components/Sidebar'

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'https://amazon-fba-saas-production.up.railway.app'

export default function PPCPage() {
  const router = useRouter()
    const [token, setToken] = useState('')
      const [loading, setLoading] = useState(true)
        const [error, setError] = useState('')
          const [campaigns, setCampaigns] = useState([])
            const [metrics, setMetrics] = useState(null)
              const [showCreateForm, setShowCreateForm] = useState(false)
                const [selectedCampaign, setSelectedCampaign] = useState(null)
                  const [campaignKeywords, setCampaignKeywords] = useState([])
                    const [loadingKeywords, setLoadingKeywords] = useState(false)

                      const [formData, setFormData] = useState({
                          name: '',
                              type: 'SP',
                                  daily_budget: '',
                                      start_date: ''
                                        })

                                          // Auth check and fetch data
                                            useEffect(() => {
                                                const storedToken = localStorage.getItem('ecomera_token')
                                                    const storedUser = localStorage.getItem('ecomera_user')

                                                        if (!storedToken || !storedUser) {
                                                              router.push('/login')
                                                                    return
                                                                        }

                                                                            setToken(storedToken)
                                                                                fetchCampaigns(storedToken)
                                                                                    fetchMetrics(storedToken)
                                                                                      }, [router])

                                                                                        const fetchCampaigns = async (authToken) => {
                                                                                            try {
                                                                                                  setLoading(true)
                                                                                                        const res = await fetch(`${API_URL}/ppc/campaigns`, {
                                                                                                                headers: {
                                                                                                                          'Authorization': 'Bearer ' + authToken,
                                                                                                                                    'Content-Type': 'application/json'
                                                                                                                                            }
                                                                                                                                                  })
                                                                                                                                                  
                                                                                                                                                        if (!res.ok) throw new Error('Failed to fetch campaigns')
                                                                                                                                                              const data = await res.json()
                                                                                                                                                                    setCampaigns(data.campaigns || [])
                                                                                                                                                                        } catch (err) {
                                                                                                                                                                              setError(err.message)
                                                                                                                                                                                  } finally {
                                                                                                                                                                                        setLoading(false)
                                                                                                                                                                                            }
                                                                                                                                                                                              }
                                                                                                                                                                                              
                                                                                                                                                                                                const fetchMetrics = async (authToken) => {
                                                                                                                                                                                                    try {
                                                                                                                                                                                                          const res = await fetch(`${API_URL}/ppc/metrics`, {
                                                                                                                                                                                                                  headers: {
                                                                                                                                                                                                                            'Authorization': 'Bearer ' + authToken,
                                                                                                                                                                                                                                      'Content-Type': 'application/json'
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                    })
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                          if (!res.ok) throw new Error('Failed to fetch metrics')
                                                                                                                                                                                                                                                                const data = await res.json()
                                                                                                                                                                                                                                                                      setMetrics(data)
                                                                                                                                                                                                                                                                          } catch (err) {
                                                                                                                                                                                                                                                                                console.error('Metrics error:', err)
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                        const fetchCampaignKeywords = async (campaignId) => {
                                                                                                                                                                                                                                                                                            if (!token) return
                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                      setLoadingKeywords(true)
                                                                                                                                                                                                                                                                                                            const res = await fetch(`${API_URL}/ppc/campaigns/${campaignId}/keywords`, {
                                                                                                                                                                                                                                                                                                                    headers: {
                                                                                                                                                                                                                                                                                                                              'Authorization': 'Bearer ' + token,
                                                                                                                                                                                                                                                                                                                                        'Content-Type': 'application/json'
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                            if (res.ok) {
                                                                                                                                                                                                                                                                                                                                                                    const data = await res.json()
                                                                                                                                                                                                                                                                                                                                                                            setCampaignKeywords(data.keywords || [])
                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                            console.error('Keywords fetch error:', err)
                                                                                                                                                                                                                                                                                                                                                                                                } finally {
                                                                                                                                                                                                                                                                                                                                                                                                      setLoadingKeywords(false)
                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                              const handleCreateCampaign = async (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                  e.preventDefault()
                                                                                                                                                                                                                                                                                                                                                                                                                      if (!token) return
                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                const res = await fetch(`${API_URL}/ppc/campaigns`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                        method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                                headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          'Authorization': 'Bearer ' + token,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Content-Type': 'application/json'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              campaign_name: formData.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type: formData.type,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  daily_budget: parseFloat(formData.daily_budget),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            start_date: formData.start_date
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (res.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setShowCreateForm(false)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setFormData({ name: '', type: 'SP', daily_budget: '', start_date: '' })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fetchCampaigns(token)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setError('Failed to create campaign')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setError(err.message)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const handlePauseCampaign = async (campaignId) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!token) return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const res = await fetch(`${API_URL}/ppc/campaigns/${campaignId}/pause`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    method: 'PUT',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'Authorization': 'Bearer ' + token,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Content-Type': 'application/json'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (res.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fetchCampaigns(token)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error('Pause error:', err)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const handleSelectCampaign = (campaign) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setSelectedCampaign(campaign)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fetchCampaignKeywords(campaign.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const getStatusColor = (status) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    switch (status?.toLowerCase()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          case 'active':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return '#00C853'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        case 'paused':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return '#FFC107'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      case 'archived':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return '#888888'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return '#2196F3'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const getTypeColor = (type) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        switch (type) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              case 'SP':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return { bg: 'rgba(33, 150, 243, 0.1)', text: '#2196F3' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case 'SB':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return { bg: 'rgba(255, 215, 0, 0.1)', text: '#FFD700' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          case 'SD':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return { bg: 'rgba(0, 200, 83, 0.1)', text: '#00C853' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return { b
